apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-api-hub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: llm-api.<your-domain>
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: llm-api-hub
              port:
                number: 80
