# ingress/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azureopengpt-tls
  namespace: default
spec:
  secretName: azureopengpt-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - azureopengpt.com
